BlogEngine6/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogEngine6.Models
{
    public class Blog
    {

        public int BlogID { get; set; }

        [Required]
        public string UserID { get; set; }

        [Display(Name = "Post Date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime PostDate { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        [StringLength(5000, MinimumLength = 10)]
        public string Content { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}

BlogEngine6/Models/ViewModels/BlogViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogEngine6.Models.ViewModels
{
    public class CreateBlogViewModel
    {
        [Required]
        [StringLength(40, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        [StringLength(5000, MinimumLength = 10)]
        public string Content { get; set; }
    }

    public class ViewBlogViewModel
    {

        public int BlogID { get; set; }

        [Display(Name = "Author")]
        public string UserName { get; set; }

        [Display(Name = "Post Date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime PostDate { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 3)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        [StringLength(5000, MinimumLength = 10)]
        public string Content { get; set; }

        public bool isFavorited { get; set; }
        public int commentCount { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }

        public ViewBlogViewModel()
        {
            isFavorited = false;
            commentCount = 0;
        }

    }

    public class FeaturedPostViewModel
    {
        [Required]
        public int BlogID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Author { get; set; }
    }

    public class CreateBlogCommentViewModel
    {
        [Required]
        public int BlogID { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [StringLength(500, MinimumLength = 3)]
        public string Message { get; set; }

    }

    public class ViewBlogCommentViewModel
    {
        [Required]
        public int BlogCommentID { get; set; }

        [Required]
        public string Author { get; set; }

        [Display(Name = "Post Date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime PostDate { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [StringLength(500, MinimumLength = 3)]
        public string Message { get; set; }

    }

}

BlogEngine6/Controllers/BlogsController.cs
using BlogEngine6.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BlogEngine6.Models.ViewModels;
using AutoMapper;
using Microsoft.AspNet.Identity;

namespace BlogEngine6.Controllers
{
    public class BlogsController : BlogBase
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        const int MAX_COMMENTS_PER_BLOG = 3;

        // GET: Blogs
        public ActionResult Index(string author, string tag, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentAuthor = author;
            ViewBag.CurrentTag = (String.IsNullOrEmpty(tag) ? null : tag);

            // Allow for paging and search filter
            if (searchString != null) {
                page = 1;
            }
            else {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = (String.IsNullOrEmpty(searchString) ? null : searchString);

            var blogs = db.Blogs.Include(b => b.User);

            // Add search string to query
            if (!String.IsNullOrEmpty(searchString)) {
                blogs = blogs.Where(b => b.User.UserName.Contains(searchString) || b.Title.Contains(searchString));
            }

            // Add author to query
            if (!String.IsNullOrEmpty(author)) {
                blogs = blogs.Where(b => b.User.UserName == author);
            }

            // Add tag to query
            if (!String.IsNullOrEmpty(tag))
            {
                blogs = blogs.Where(x => x.Tags.Any(p2 => p2.Name == tag));

            }

            blogs = blogs.OrderByDescending(b => b.PostDate);

            List<ViewBlogViewModel> blogList = blogs.AsEnumerable()
                          .Select(b => new ViewBlogViewModel
                          {
                              BlogID = b.BlogID,
                              UserName = b.User.UserName,
                              PostDate = b.PostDate,
                              Title = b.Title,
                              Content = b.Content,
                              Tags = b.Tags,
                              isFavorited = false,
                              commentCount = 0
                          }).ToList();

            blogList = checkFavorites(blogList);
            blogList = setNumComments(blogList);

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(blogList.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Blog blog = db.Blogs.Find(id);

            if (blog == null)
            {
                return HttpNotFound();
            }

            ViewBlogViewModel blogViewModel = new ViewBlogViewModel
            {
                BlogID = blog.BlogID,
                UserName = blog.User.UserName,
                PostDate = blog.PostDate,
                Title = blog.Title,
                Content = blog.Content
            };

            blogViewModel = checkFavorites(blogViewModel);
            return View(blogViewModel);
        }

        public async Task<ActionResult> DetailsJSON(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Blog blog = await db.Blogs.FindAsync(id);

            if (blog == null)
            {
                return HttpNotFound();
            }

            var blogJSON = new Dictionary<string, string>();

            blogJSON["Title"] = blog.Title;
            blogJSON["PostDate"] = blog.PostDate.ToString();

            return Json(blogJSON, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> FavoritePost(int blogID)
        {
            string userID = User.Identity.GetUserId();
            FavoriteBlog checkFBlog = db.FavoriteBlogs.SingleOrDefault(b => b.BlogID == blogID && b.UserID == userID);

            try
            {
                // If post is already favorited, remove favorite
                if (checkFBlog != null)
                {
                    db.FavoriteBlogs.Remove(checkFBlog);
                    db.SaveChanges();

                    return Json(new { success = true, isAdded = false, blogId = blogID });
                }

                FavoriteBlog fBlog = new FavoriteBlog();

                fBlog.BlogID = blogID;
                fBlog.UserID = userID;
                db.FavoriteBlogs.Add(fBlog);

                await db.SaveChangesAsync();

                return Json(new { success = true, isAdded = true, blogId = blogID });
                
            }
            catch (Exception)
            {
                return Json(new { success = false, msg = "An unknown error occured." });
            }
        }

        [Authorize]
        public ActionResult Favorites(int? page)
        {
            // Get all user favorited blogs
            string userID = User.Identity.GetUserId();
            var fBlogs = db.FavoriteBlogs.Where(b => b.UserID == userID).OrderByDescending(b => b.Blog.PostDate);

            List<ViewBlogViewModel> blogList = fBlogs.AsEnumerable()
                          .Select(b => new ViewBlogViewModel
                          {
                              BlogID = b.BlogID,
                              UserName = b.User.UserName,
                              PostDate = b.Blog.PostDate,
                              Title = b.Blog.Title,
                              Content = b.Blog.Content,
                              Tags = b.Blog.Tags,
                              isFavorited = true
                          }).ToList();

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PostComment([Bind(Include = "BlogID,Message")] CreateBlogCommentViewModel comment)
        {
            try
            {
                string userID = User.Identity.GetUserId();
                var commentCount = db.BlogComments.Where(b => b.BlogID == comment.BlogID && b.UserID == userID).Count();

                if(commentCount > MAX_COMMENTS_PER_BLOG)
                {
                    return Json(new { success = false, msg = "Comment cannot be posted. You can only post a maximum of " + MAX_COMMENTS_PER_BLOG + " comments per blog." });
                }

                BlogComment newComment = new BlogComment();

                if (ModelState.IsValid)
                {
                    newComment.BlogID = comment.BlogID;
                    newComment.Message = comment.Message;
                    newComment.UserID = userID;
                    newComment.PostDate = DateTime.Now;
                    db.BlogComments.Add(newComment);

                    await db.SaveChangesAsync();

                    return Json(new { success = true, blogId = comment.BlogID });
                }
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            return Json(new { success = false, msg = "Comment not posted. An unknown error occured." });
        }


        [ChildActionOnly]
        public ActionResult FeaturedPosts()
        {
            var featuredBlogs = db.FeaturedBlogs
                                .OrderBy(b => b.FeatureDate).Take(5);

            List<FeaturedPostViewModel> blogList = featuredBlogs.AsEnumerable()
                          .Select(b => new FeaturedPostViewModel
                          {
                              BlogID = b.BlogID,
                              Title = b.Blog.Title,
                              Author = b.Blog.User.UserName
                          }).ToList();

            ViewBag.Title = "Editors’ picks";
            ViewBag.Description = "Stories that matter.";

            return PartialView("SidebarPostsPartial", blogList);
        }

        [ChildActionOnly]
        public ActionResult RandomPosts()
        {
            // Get random blog based on generated GUID
            var featuredBlogs = db.Blogs
                                .OrderBy(b => b.PostDate)
                                .OrderBy(r => Guid.NewGuid()).Take(5);

            List<FeaturedPostViewModel> blogList = featuredBlogs.AsEnumerable()
                          .Select(b => new FeaturedPostViewModel
                          {
                              BlogID = b.BlogID,
                              Title = b.Title,
                              Author = b.User.UserName
                          }).ToList();

            ViewBag.Title = "Reading roulette";
            ViewBag.Description = "The new variety hour.";

            return PartialView("SidebarPostsPartial", blogList);
        }

        [ChildActionOnly]
        public ActionResult FavoriteStories()
        {

            // Get top occuring blogs from favorite blogs table
            var favBlogs = (from blogs in db.FavoriteBlogs
                           group blogs by blogs.BlogID into blogGroup
                           select new FeaturedPostViewModel
                           {
                               BlogID = blogGroup.Key,
                               Title = blogGroup.Select(b => b.Blog.Title).FirstOrDefault(),
                               Author = blogGroup.Select(b => b.Blog.User.UserName).FirstOrDefault(),
                           }).Take(5).ToList();

            ViewBag.Title = "Top Stories";

BlogEngine6/Views/Blogs/BlogCommentsFormPartial.cshtml
@model BlogEngine6.Models.ViewModels.CreateBlogCommentViewModel

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()

    <div class="blogCommentForm">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" name="BlogID" value=@ViewBag.BlogID />
        <div class="form-group">
            @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", @placeholder = "Give your feedback..." } })
            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="button" value="Post" class="btn btn-success" onclick="postBlogComment(this, @ViewBag.Count);" />
        </div>

    </div>
    }
}
else{
    <p>Please log in to post a comment.</p>
}

BlogEngine6/Views/Blogs/BlogCommentsPartial.cshtml
@model IEnumerable<BlogEngine6.Models.ViewModels.ViewBlogCommentViewModel>


<div class="blogCommentArea">
    <h3>Comments</h3>
    @{Html.RenderAction("BlogCommentsForm", "Blogs", new { id = @ViewBag.BlogID, count = ViewBag.Count });}
    <hr />    
    <div>

        @foreach (var item in Model)
        {
            <div class="commentItem" data-id=@item.BlogCommentID>
                <div style="float: right;" >
                    @if (Request.IsAuthenticated && User.IsInRole("Editor"))
                    {
                            using (Html.BeginForm(null, null, null, FormMethod.Post, new { @style = "display: inline-block;" }))
                            {
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="id" value=@item.BlogCommentID />
                                <input type="button" value="X" class="btn btn-danger"  onclick="deleteComment_Confirm(this);" />
                            }
                    }
                </div>
                <p>@Html.DisplayFor(modelItem => item.Author)</p>
                <p><i>@Html.DisplayFor(modelItem => item.PostDate)</i></p>
                <p>
                    @Html.DisplayFor(modelItem => item.Message)
                </p>
                <hr />
            </div>
        }

    </div>

    @if (Model.Count() > 0){
        <div class="loadMoreDiv">
            <button type="button" class="btn btn-danger" style="text-align: center;" onclick="$('.blogCommentArea').load('/Blogs/BlogComments?id=' + @ViewBag.BlogID +'&count='+( @ViewBag.Count+5))">Load More...</button>
        </div>
    }

</div>

BlogEngine6/Views/Blogs/Details.cshtml
@model BlogEngine6.Models.ViewModels.ViewBlogViewModel

@{
    ViewBag.Title = "Details";
}

<div>
    <h2>@Html.DisplayFor(model => model.Title)</h2>
    <p><a class="blogPostAuthor" href="@Url.Action("Index","Blogs", new { author=Model.UserName }, Request.Url.Scheme)">@Html.DisplayFor(model => model.UserName)</a></p>
    <p>@Html.DisplayFor(model => model.PostDate)</p>

    <hr />
    <div>
        @Html.Raw(Model.Content)
    </div>
</div>
<div id="counter"></div>

<script>
    var n = BlogID.getItem('on_load_counter');

    if (n === null) {
        n = 0;
    }

    n++; 
    BlogID.setItem("on_load_counter", n);
    
    document.getElementById('counter').innerHTML ="Views: "+ n;
</script>


@Html.Partial("Blogs/FavoritePostFormPartial", Model)
@{Html.RenderAction("BlogComments", "Blogs", new { id = Model.BlogID, count = 5 });}

BlogEngine6/Views/Blogs/Favorites.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<BlogEngine6.Models.ViewModels.ViewBlogViewModel>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Favorite Blogs";
}

<div class="blogList">
    <div class="blogListBody home">
        <h3>Stories you love...</h3>
        @foreach (var item in Model)
        {
            @Html.Partial("Blogs/BlogPostPartial", item)
        }

        <br />
    </div>
    <div class="sideBar">

        @if (Request.IsAuthenticated)
        {
            <p>@Html.ActionLink("Browse Blogs", "Index", "Blogs")</p>
        }

        @{Html.RenderAction("FeaturedPosts", "Blogs");}
        @{Html.RenderAction("FavoriteStories", "Blogs");}
        @{Html.RenderAction("RandomPosts", "Blogs");}
        @{Html.RenderAction("BlogTags", "Blogs");}
    </div>
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Favorites", new { page, currentFilter = ViewBag.CurrentFilter, author = ViewBag.CurrentAuthor }))

BlogEngine6/Views/Blogs/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<BlogEngine6.Models.ViewModels.ViewBlogViewModel>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Blogs";
}

<div class="row blogSearch">

    <div class="col-xs-6 col-sm-4">
    @using (Html.BeginForm("Index", "Blogs", FormMethod.Get))
        {

            if (ViewBag.CurrentAuthor != null)
                {
                <input type="hidden" name="author" value="@ViewBag.CurrentAuthor">
        }
            if (ViewBag.CurrentTag != null)
            {
                <input type="hidden" name="tag" value="@ViewBag.CurrentTag">
            }
            <label for="SearchString">Search:</label>
            <p>
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { placeholder = "Title or Author" })
                <input type="submit" value="Go" class="btn btn-primary submitBtn" />
            </p>
        }
    </div>

    @if (ViewBag.CurrentAuthor != null)
    {
        <div class="col-xs-6 col-sm-4">
            <a href="@Url.Action("Index", "Blogs", new { currentFilter=ViewBag.CurrentFilter, tag=ViewBag.CurrentTag }, Request.Url.Scheme)" class="blogFilterAnchor">
                <div><div><span>X</span></div><b>Author:</b> @ViewBag.CurrentAuthor</div>
            </a>
        </div>
    }

    @if (ViewBag.CurrentFilter != null)
    {
        <div class="col-xs-6 col-sm-4">
            <a href="@Url.Action("Index", "Blogs", new { author = ViewBag.CurrentAuthor, tag=ViewBag.CurrentTag }, Request.Url.Scheme)" class="blogFilterAnchor">
                <div><div><span>X</span></div><b>Filter:</b> <span>@ViewBag.CurrentFilter</span></div>
            </a>
        </div>
    }

    @if (ViewBag.CurrentTag != null)
    {
        <div class="col-xs-6 col-sm-4">
            <a href="@Url.Action("Index", "Blogs", new { author = ViewBag.CurrentAuthor, currentFilter = ViewBag.CurrentFilter }, Request.Url.Scheme)" class="blogFilterAnchor">
                <div><div><span>X</span></div><b>Tag:</b> <span>@ViewBag.CurrentTag</span></div>
            </a>
        </div>
    }

</div>


<div class="blogList">

    <div class="blogListBody">
        @foreach (var item in Model)
        {
           @Html.Partial("Blogs/BlogPostPartial", item)
        }

        <br />
    </div>
    <div class="sideBar">

        @if (Request.IsAuthenticated)
        {
            <p><i class="fa fa-heart" style="color: red;" aria-hidden="true"></i> @Html.ActionLink("Favorite Blogs", "Favorites", "Blogs")</p>
        }

        @{Html.RenderAction("FeaturedPosts", "Blogs");}
        @{Html.RenderAction("FavoriteStories", "Blogs");}
        @{Html.RenderAction("RandomPosts", "Blogs");}
        @{Html.RenderAction("BlogTags", "Blogs");}
    </div>
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, author = ViewBag.CurrentAuthor }))

BlogEngine6/Views/Blogs/SidebarPostsPartial.cshtml
@model IEnumerable<BlogEngine6.Models.ViewModels.FeaturedPostViewModel>



<div class="areaHeader">
    <div class="areaTitle">@ViewBag.Title</div>
    <div class="areaDescription">@ViewBag.Description</div>
</div>

<ul class="featuredPostsList">

@foreach (var item in Model)
{
    <li>
        <div class="blogTitle"><a href="@Url.Action("Details", "Blogs", new { id=item.BlogID }, Request.Url.Scheme)">@Html.DisplayFor(modelItem => item.Title)</a></div>
        <div class="blogAuthor"><a href="@Url.Action("Index", "Blogs", new { author=item.Author }, Request.Url.Scheme)">@Html.DisplayFor(modelItem => item.Author)</a></div>
    </li>
}

</ul>

BlogEngine6/Views/Blogs/SidebarTagsPartial.cshtml
@model IEnumerable<BlogEngine6.Models.Tag>

<div class="areaHeader">
    <div class="areaTitle">Popular Tags</div>
</div>

<div class="tagList">

    @foreach (var item in Model)
    {
        <a href="@Url.Action("Index", "Blogs", new { tag=item.Name}, Request.Url.Scheme)">@Html.DisplayFor(modelItem => item.Name)</a>
    }

</div>