BlogEngine6/Controllers/MyBlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogEngine6.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity.Infrastructure;
using BlogEngine6.Models.ViewModels;
using PagedList;

namespace BlogEngine6.Controllers
{
    public class MyBlogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        const int MAX_BLOG_TAGS = 3;

        // GET: MyBlog
        [Authorize]
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

            // Allow for paging and search filter
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = (String.IsNullOrEmpty(searchString) ? null : searchString);

            var userID = User.Identity.GetUserId();
            var blogs = db.Blogs.Include(b => b.User).Where(b => b.UserID == userID);

            // Add search string to query
            if (!String.IsNullOrEmpty(searchString))
            {
                blogs = blogs.Where(b => b.User.UserName.Contains(searchString) || b.Title.Contains(searchString));
            }


            blogs = blogs.OrderByDescending(b => b.PostDate);

            List<ViewBlogViewModel> blogList = blogs.AsEnumerable()
                          .Select(o => new ViewBlogViewModel
                          {
                              BlogID = o.BlogID,
                              UserName = o.User.UserName,
                              PostDate = o.PostDate,
                              Title = o.Title,
                              Content = o.Content,
                              Tags = o.Tags
                          }).ToList();

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Blog blog = db.Blogs.Find(id);
            var userID = User.Identity.GetUserId();

            if (blog == null)
            {
                return HttpNotFound();
            }
            else if (blog.UserID != userID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            ViewBlogViewModel blogViewModel = new ViewBlogViewModel{
                                        BlogID = blog.BlogID,
                                        UserName = blog.User.UserName,
                                        PostDate = blog.PostDate,
                                        Title = blog.Title,
                                        Content = blog.Content
                                    };

            return View(blogViewModel);
        }


        // GET: MyBlog/Create
        [Authorize]
        public ActionResult Create()
        {

            IEnumerable<Tag> tags = db.Tags.OrderBy(b => b.Name ).ToList();
            ViewBag.BlogTags = tags;

            return View();
        }

       
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Title,Content")] CreateBlogViewModel blog, string[] selectedTags)
        {
           try
            {
                Blog newBlog = new Blog();

                if (selectedTags != null)
                {

                    if (selectedTags.Length > MAX_BLOG_TAGS)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }

                    newBlog.Tags = new List<Tag>();
                    foreach (var tag in selectedTags)
                    {
                        var taggtoAdd = db.Tags.Find(int.Parse(tag));
                        newBlog.Tags.Add(taggtoAdd);
                    }
                }

                if (ModelState.IsValid)
                {
                    newBlog.Title = blog.Title;
                    newBlog.Content = blog.Content;
                    newBlog.UserID = User.Identity.GetUserId();
                    newBlog.PostDate = DateTime.Now;
                    db.Blogs.Add(newBlog);

                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            return View(blog);
        }


        // GET: MyBlog/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Blog blog = db.Blogs.Find(id);
            var userID = User.Identity.GetUserId();

            if (blog == null)
            {
                return HttpNotFound();
            }
            else if (blog.UserID != userID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBlogViewModel blogViewModel = new ViewBlogViewModel
            {
                BlogID = blog.BlogID,
                UserName = blog.User.UserName,
                PostDate = blog.PostDate,
                Title = blog.Title,
                Content = blog.Content,
                Tags = blog.Tags
            };

            IEnumerable<Tag> tags = db.Tags.OrderBy(b => b.Name).ToList();
            ViewBag.BlogTags = tags;

            return View(blogViewModel);
        }
        
        [Authorize]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, string[] selectedTags)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userID = User.Identity.GetUserId();
            var blogToUpdate = db.Blogs.Find(id);

            if (blogToUpdate.UserID != userID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (selectedTags != null && selectedTags.Length > MAX_BLOG_TAGS)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (TryUpdateModel(blogToUpdate, "",
               new string[] { "Title", "Content" }))
            {
                try
                {

                    UpdateBlogTags(selectedTags, blogToUpdate);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(blogToUpdate);
        }

        private void UpdateBlogTags(string[] selectedTags, Blog blogToUpdate)
        {

            if (selectedTags == null)
            {
                blogToUpdate.Tags.Clear();
                return;
            }

            // Get selected tags and all tags from DB
            var selectedTagsHS = new HashSet<string>(selectedTags);
            var blogTags = new HashSet<int>
                (blogToUpdate.Tags.Select(c => c.TagID));
                
            // Loop through DB tags
            foreach (var tag in db.Tags)
            {
                // If tag is one of the selected ones, add it, else remove it
                if (selectedTagsHS.Contains(tag.TagID.ToString()))
                {
                    if (!blogTags.Contains(tag.TagID))
                    {
                        blogToUpdate.Tags.Add(tag);
                    }
                }
                else
                {
                    if (blogTags.Contains(tag.TagID))
                    {
                        blogToUpdate.Tags.Remove(tag);
                    }
                }
            }
        }


        // POST: MyBlog/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var userID = User.Identity.GetUserId();
            Blog blog = await db.Blogs.FindAsync(id);

            if(blog.UserID == userID)
            {
                db.Blogs.Remove(blog);
                await db.SaveChangesAsync();

                return Json(new { success = true, blogId = id });
            }

            return Json(new { success = false });

        }


        public ActionResult BlogTagsJSON()
        {

           var tags = db.Tags.Select(c => new { c.TagID, c.Name});

            return Json(tags, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogEngine6/Views/MyBlog/Create.cshtml
@model BlogEngine6.Models.ViewModels.CreateBlogViewModel

@{
    ViewBag.Title = "New Blog Post";
}

<h2>New Blog Post</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal blogForm">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       


        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="Content">Tell your story...</label>
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @id = "createBlogContentInput", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>

        <div class="row form-group">
            <div class="col-xs-4">
                <button class="btn btn-warning showBlogTags" onclick="$('.blogTagsDiv').slideToggle(); return false;">Tag it!</button>
                &nbsp;<a class="btn btn-primary" href="../Tags/Index" role="button">Add Tags</a>&nbsp;&nbsp;
               <input type="submit" value="Post" class="btn btn-success submitBtn" /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <div class="form-group blogTagsDiv" style="display: none;">
                    <select multiple="multiple" id="tagSelect" name="selectedTags">
                        @{
                            List<BlogEngine6.Models.Tag> tags = ViewBag.BlogTags;

                            foreach (var tag in tags)
                            {
                                <option value='@tag.TagID'>@tag.Name</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="col-xs-8">
               &nbsp;</div>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/Custom/jquery.multi-select.js"></script>
    <script>
        //$.validator.setDefaults({ ignore: '' });
        CKEDITOR.replace('createBlogContentInput');
        $('#tagSelect').multiSelect();
    </script>
}

BlogEngine6/Views/MyBlog/Details.cshtml
@model BlogEngine6.Models.ViewModels.ViewBlogViewModel


@{
    ViewBag.Title = "Details";
}

<div>
    <h2>@Html.DisplayFor(model => model.Title)</h2>
    <p>@Html.DisplayFor(model => model.PostDate)</p>

    <div style="margin-top: 15px;">
        <p style="display: inline-block;">@Html.ActionLink("Edit", "Edit", new { id = Model.BlogID }, new { @class = "btn btn-warning" })</p>

        @using (Html.BeginForm(null, null, null, FormMethod.Post, new { @style = "display: inline-block;" }))
            {
            @Html.AntiForgeryToken()
            <input type="hidden" name="id" value=@Model.BlogID />
            <input type="button" value="Delete" class="btn btn-danger" onclick="deleteBlogItem_Confirm(this, true);" />
        }

    </div>

    <hr />
    <div>
        @Html.Raw(Model.Content)
    </div>
</div>
  <div id="counter"></div>

<script>
    var n = BlogID.getItem('on_load_counter');

    if (n === null) {
        n = 0;
    }

    n++;
    BlogID.setItem("on_load_counter", n);
    
    document.getElementById('counter').innerHTML ="Views: "+ n;
</script>

BlogEngine6/Views/MyBlog/Edit.cshtml
@model BlogEngine6.Models.ViewModels.ViewBlogViewModel

@{
    ViewBag.Title = "Edit Blog Post";
}

<h2>Edit Blog Post</h2>


@using (Html.BeginForm(null, null, null, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal blogForm">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="Content">Tell your story...</label>
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @id = "editBlogContentInput", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>

        <div class="row form-group">
            <div class="col-xs-4">
                <button class="btn btn-warning showBlogTags" onclick="$('.blogTagsDiv').slideToggle(); return false;">Tag it!</button>
                <div class="form-group blogTagsDiv" style="display: none;">
                    <select multiple="multiple" id="tagSelect" name="selectedTags">
                        @{
                            List<BlogEngine6.Models.Tag> tags = ViewBag.BlogTags;

                            foreach (var tag in tags)
                            {
                                <option value='@tag.TagID' @(Model.Tags.Contains(tag) ? "selected" : "")>@tag.Name</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="col-xs-8">
                <input id="editBlogSubmit" type="submit" value="Post" class="btn btn-success submitBtn" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/Custom/jquery.multi-select.js"></script>
    <script>
         $.validator.setDefaults({ ignore: '' });
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
         CKEDITOR.replace('editBlogContentInput');
         $('#tagSelect').multiSelect();
    </script>

}

BlogEngine6/Views/MyBlog/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<BlogEngine6.Models.ViewModels.ViewBlogViewModel>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "My Blog";
}

<div class="row blogSearch">
    <div class="col-xs-6 col-sm-4">
        @using (Html.BeginForm("Index", "MyBlog", FormMethod.Get))
        {
            <div>
                <label for="SearchString">Search:</label>
                <p>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { placeholder = "Title" })
                    <input type="submit" value="Go" class="btn btn-primary submitBtn" />
                </p>
            </div>
        }
        <p>
            @Html.ActionLink("New Blog Post", "Create", null, new { @class = "btn btn-success" })
        </p>
    </div>

    @if (ViewBag.CurrentFilter != null)
    {
        <div class="col-xs-6 col-sm-4">
            <a href="@Url.Action("Index", "MyBlog", new { author = ViewBag.CurrentAuthor }, Request.Url.Scheme)" class="blogFilterAnchor">
                <div><div><span>X</span></div><b>Filter:</b> <span>@ViewBag.CurrentFilter</span></div>
            </a>
        </div>
    }

</div>


@foreach (var item in Model)
{
    <div class="row blogItem" data-id=@item.BlogID>
        <div class="col-md-10">

            <div>
                <h3 class="blogPostTitle">@Html.DisplayFor(modelItem => item.Title)</h3>
                <p class="blogPostDate">@Html.DisplayFor(modelItem => item.PostDate)</p>
                <div class="blogPostContent">
                    @Html.Raw(item.Content)
                    <div class="fadeHelper"></div>
                </div>
            </div>
           
            <p class="viewMore"><a href="@Url.Action("Details", "MyBlog", new { id=item.BlogID }, Request.Url.Scheme)">View more...</a></p>
            <p class="blogTags">
                @foreach (var tag in item.Tags)
                {
                    <i class="fa fa-tag" aria-hidden="true"></i> @Html.DisplayFor(modelItem => tag.Name)
                }
            </p>
        </div>
        <div class="col-md-2 blogButtons">
            <p>@Html.ActionLink("Edit", "Edit", new { id = item.BlogID }, new { @class = "btn btn-warning" })</p>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="id" value=@item.BlogID />
                <input type="button" value="Delete" class="btn btn-danger" onclick="deleteBlogItem_Confirm(this, false);" />
            }

</div>
    </div>

}

<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter, author = ViewBag.CurrentAuthor }))